[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
cache = true
cache_path = 'cache'
broadcast = 'broadcast'
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    'forge-std/=lib/forge-std/src/',
]

# Avalanche Fuji testnet configuration
[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
mainnet = "https://api.avax.network/ext/bc/C/rpc"
local = "http://localhost:9650/ext/bc/C/rpc"

# Etherscan configuration for contract verification
[etherscan]
fuji = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
avalanche = { key = "${ETHERSCAN_API_KEY}", url = "https://api.snowtrace.io/api" }

# Test settings
[profile.default.fuzz]
runs = 1000

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }
